name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Verify
        run: npm run verify
